// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as TestCli from "./TestCli.mjs";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Vitest$1 from "@epure/vitest";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodechild_process from "node:child_process";

let ranPage = (async path => {
  const root = { textContent: "", className: "" };
  globalThis.document = {
    getElementById: id => (id === "root" ? root : null),
    querySelector: () => null,
    createElement: () => ({ relList: { supports: () => false } }),
    querySelectorAll: () => [],
    head: { appendChild: () => {} },
    addEventListener: () => {},
  };
  globalThis.window = {
    location: { search: "", pathname: "/" },
    localStorage: { getItem: () => null, setItem: () => {} },
    history: { replaceState: () => {} },
  };
  globalThis.MutationObserver = class { observe() {} disconnect() {} };
  await import(path);
  delete globalThis.document;
  delete globalThis.window;
  delete globalThis.MutationObserver;
  return root.textContent;
});

Vitest$1.Given("an empty working directory", (param, context) => {
  let step = param.step;
  let scratch = {
    contents: undefined
  };
  let last = {
    contents: undefined
  };
  context.onTestFinished(async param => Stdlib_Option.forEach(scratch.contents, TestCli.System.forget));
  let place = () => {
    let root = scratch.contents;
    if (root !== undefined) {
      return root;
    }
    let root$1 = TestCli.System.scratch();
    scratch.contents = root$1;
    return root$1;
  };
  let root = () => {
    let root$1 = scratch.contents;
    if (root$1 !== undefined) {
      return root$1;
    } else {
      return Nodepath.dirname(TestCli.golden().project);
    }
  };
  let manifest = () => JSON.parse(Nodefs.readFileSync(Nodepath.join(TestCli.golden().project, "package.json"), "utf8"));
  let section = name => {
    let fields = manifest();
    if (typeof fields !== "object" || fields === null || Array.isArray(fields)) {
      return [];
    }
    let match = fields[name];
    if (match !== undefined) {
      if (typeof match === "object" && match !== null && !Array.isArray(match)) {
        return Object.keys(match);
      } else {
        return [];
      }
    } else {
      return [];
    }
  };
  let building = () => {
    let env = Object.fromEntries(Object.entries(process.env));
    env["NODE_ENV"] = "production";
    return env;
  };
  let runs = (script, name) => {
    let ran = Nodechild_process.spawnSync("pnpm", [script], {
      cwd: TestCli.golden().project,
      stdio: "pipe",
      encoding: "utf8",
      env: building()
    });
    let status = Stdlib_Option.getOr(Primitive_option.fromNullable(ran.status), -1);
    if (status !== 0) {
      console.error(name + ` failed:`);
      console.error(ran.stdout);
      console.error(ran.stderr);
    }
    return status;
  };
  step("Theo initializes a project named {string}", async name => {
    let root = scratch.contents;
    if (root !== undefined) {
      last.contents = await TestCli.runs([
        "init",
        name
      ], root, undefined);
      return;
    }
  });
  step("Theo creates a project named {string} with no command", async name => {
    last.contents = await TestCli.runs([name].concat(TestCli.links), place(), undefined);
  });
  step("Theo runs epure with {string}", async word => {
    last.contents = await TestCli.runs([word], place(), undefined);
  });
  step("{string} names the project {string}", (path, name) => {
    let fields = JSON.parse(Nodefs.readFileSync(Nodepath.join(root(), path), "utf8"));
    if (typeof fields === "object" && fields !== null && !Array.isArray(fields)) {
      return Vitest.expect(fields["name"]).toEqual(name);
    } else {
      return Vitest.expect(path).toBe("an object");
    }
  });
  step("Theo initializes a project named {string} against {string}", async (name, registry) => {
    last.contents = await TestCli.runs([
      "init",
      name,
      "--registry",
      registry
    ].concat(TestCli.links), place(), undefined);
  });
  step("{string} does not exist", path => Vitest.expect([
    path,
    Nodefs.existsSync(Nodepath.join(root(), path))
  ]).toEqual([
    path,
    false
  ]));
  step("{string} exists", path => Vitest.expect([
    path,
    Nodefs.existsSync(Nodepath.join(root(), path))
  ]).toEqual([
    path,
    true
  ]));
  step("{string} contains the method files", (dir, table) => {
    Vitest$1.toRecords(table).forEach(row => {
      let path = Nodepath.join(dir, row.file);
      Vitest.expect([
        row.file,
        Nodefs.existsSync(Nodepath.join(root(), path))
      ]).toEqual([
        row.file,
        true
      ]);
    });
  });
  step("the installed packages carry a reference", table => {
    Vitest$1.toRecords(table).forEach(row => {
      let reference = Nodepath.join(TestCli.golden().project, Nodepath.join("node_modules", Nodepath.join(row.package, "llms.txt")));
      Vitest.expect([
        row.package,
        Nodefs.existsSync(reference)
      ]).toEqual([
        row.package,
        true
      ]);
    });
  });
  step("{string} contains the stack dependencies", (param, table) => {
    let held_0 = section("dependencies");
    let held_1 = section("devDependencies");
    Vitest$1.toRecords(table).forEach(row => {
      let where = row.type === "dev dependency" ? held_1 : held_0;
      Vitest.expect([
        row.dependency,
        where.includes(row.dependency)
      ]).toEqual([
        row.dependency,
        true
      ]);
    });
  });
  step("{string} contains {string}", (path, text) => Vitest.expect(Nodefs.readFileSync(Nodepath.join(root(), path), "utf8")).toContain(text));
  step("{string} contains the diagonal layout", (dir, table) => {
    Vitest$1.toRecords(table).forEach(row => {
      let path = Nodepath.join(dir, row.directory);
      let path$1 = Nodepath.join(root(), path);
      let holds = Nodefs.existsSync(path$1) && Nodefs.statSync(path$1).isDirectory() && Nodefs.readdirSync(path$1).length !== 0;
      Vitest.expect([
        row.directory,
        holds
      ]).toEqual([
        row.directory,
        true
      ]);
    });
  });
  step("the project dependencies are installed", () => Vitest.expect(Nodefs.existsSync(Nodepath.join(TestCli.golden().project, "node_modules"))).toBe(true));
  step("the project builds successfully", () => Vitest.expect(runs("build", "build")).toBe(0));
  step("the project tests pass", () => Vitest.expect(runs("test", "test")).toBe(0));
  let bundle = () => {
    Vitest.expect(runs("build", "build")).toBe(0);
    let page = Nodefs.readFileSync(Nodepath.join(TestCli.golden().project, "dist/index.html"), "utf8");
    let result = page.match(/\/assets\/[^\"]+\.js/);
    if (result == null) {
      return Stdlib_JsError.throwWithMessage("the built page names no script");
    } else {
      return Nodepath.join(TestCli.golden().project, "dist" + result[0]);
    }
  };
  step("the built page says {string}", async text => {
    let said = await ranPage("file://" + bundle());
    return Vitest.expect(said).toContain(text);
  });
  step("the built page carries no board", () => Vitest.expect(Nodefs.readFileSync(bundle(), "utf8").includes("close the board")).toBe(false));
  step("the {string} directory contains a file", name => {
    let dir = Nodepath.join(place(), name);
    Nodefs.mkdirSync(dir, {
      recursive: true
    });
    Nodefs.writeFileSync(Nodepath.join(dir, "kept.txt"), "kept");
  });
  step("init fails and reports {string}", name => {
    let ran = last.contents;
    let ran$1 = ran !== undefined ? ran : Stdlib_JsError.throwWithMessage("init did not run");
    Vitest.expect(ran$1.code === 0).toBe(false);
    Vitest.expect(ran$1.complained).toContain(name);
  });
});

export {
  ranPage,
}
/* ranPage Not a pure module */
