// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Semver from "semver";
import * as Vitest from "vitest";
import * as TestCli from "./TestCli.mjs";
import * as Nodefs from "node:fs";
import * as Nodehttp from "node:http";
import * as Nodepath from "node:path";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Vitest$1 from "@epure/vitest";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let raise = Stdlib_JsError.throwWithMessage;

let sections = [
  "dependencies",
  "devDependencies"
];

function specs(file) {
  let found = {};
  let fields = JSON.parse(Nodefs.readFileSync(file, "utf8"));
  if (typeof fields === "object" && fields !== null && !Array.isArray(fields)) {
    sections.forEach(section => {
      let match = fields[section];
      if (match === undefined) {
        return;
      }
      if (typeof match !== "object" || match === null || Array.isArray(match)) {
        return;
      }
      Object.entries(match).forEach(param => {
        let spec = param[1];
        if (typeof spec !== "string") {
          return;
        }
        found[param[0]] = spec;
      });
    });
  }
  return found;
}

function named(file, $$package) {
  let spec = specs(file)[$$package];
  if (spec !== undefined) {
    return spec;
  } else {
    return Stdlib_JsError.throwWithMessage(`the template names no ` + $$package);
  }
}

Vitest$1.Given("a registry answering for the template's dependencies", (param, context) => {
  let step = param.step;
  let scratch = TestCli.System.scratch();
  let template = Nodepath.join(scratch, "package.json");
  Nodefs.writeFileSync(template, Nodefs.readFileSync(Nodepath.join(TestCli.$$package, "templates/package.json"), "utf8"));
  let before = Nodefs.readFileSync(template, "utf8");
  let published = {};
  Object.keys(specs(template)).forEach(name => {
    published[name] = Object.fromEntries([
      [
        "latest",
        "1.2.3"
      ],
      [
        "beta",
        "1.2.3-beta.4"
      ]
    ]);
  });
  let answering = {
    contents: true
  };
  let listener = Nodehttp.createServer((request, reply) => {
    let name = decodeURIComponent(request.url).slice(1);
    let tags = published[name];
    if (tags !== undefined) {
      reply.writeHead(200, Object.fromEntries([[
          "content-type",
          "application/json"
        ]]));
      reply.end(JSON.stringify(Object.fromEntries([
        [
          "name",
          name
        ],
        [
          "dist-tags",
          Object.fromEntries(Object.entries(tags).map(param => [
            param[0],
            param[1]
          ]))
        ]
      ])));
    } else {
      reply.writeHead(404, Object.fromEntries([[
          "content-type",
          "application/json"
        ]]));
      reply.end("{}");
    }
  });
  let port = {
    contents: 0
  };
  let listening = new Promise((resolve, _reject) => {
    listener.listen(0, "127.0.0.1", () => {
      port.contents = listener.address().port;
      resolve();
    });
  });
  let ran = {
    contents: {
      said: "",
      complained: "",
      code: 0
    }
  };
  context.onTestFinished(async param => {
    if (answering.contents) {
      await new Promise((resolve, _reject) => {
        listener.close(() => resolve());
      });
    }
    return TestCli.System.forget(scratch);
  });
  let sets = ($$package, tag, version) => {
    let tags = published[$$package];
    if (tags !== undefined) {
      tags[tag] = version;
    } else {
      published[$$package] = Object.fromEntries([[
          tag,
          version
        ]]);
    }
  };
  let served = $$package => {
    let tags = published[$$package];
    if (tags === undefined) {
      return Stdlib_JsError.throwWithMessage(`nothing is published for ` + $$package);
    }
    let match = tags["latest"];
    let match$1 = tags["beta"];
    if (match !== undefined) {
      return match;
    } else if (match$1 !== undefined) {
      return match$1;
    } else {
      return Stdlib_JsError.throwWithMessage(`nothing is published for ` + $$package);
    }
  };
  step("{string} is published at {string}", ($$package, version) => {
    sets($$package, "latest", version);
    sets($$package, "beta", version);
  });
  step("{string} is published at {string} as {string}", ($$package, version, tag) => sets($$package, tag, version));
  step("{string} is published at {string} as {string} only", ($$package, version, tag) => {
    published[$$package] = Object.fromEntries([[
        tag,
        version
      ]]);
  });
  step("{string} is not published", $$package => Stdlib_Dict.$$delete(published, $$package));
  step("the registry does not answer", async () => {
    await listening;
    await new Promise((resolve, _reject) => {
      listener.close(() => resolve());
    });
    answering.contents = false;
  });
  step("the template already names {string} at {string}", ($$package, spec) => {
    let json = JSON.parse(Nodefs.readFileSync(template, "utf8"));
    if (typeof json === "object" && json !== null && !Array.isArray(json)) {
      sections.forEach(section => {
        let match = json[section];
        if (match !== undefined && typeof match === "object" && match !== null && !Array.isArray(match) && Stdlib_Option.isSome(match[$$package])) {
          match[$$package] = spec;
          return;
        }
      });
    }
    Nodefs.writeFileSync(template, JSON.stringify(json, undefined, 2) + "\n");
  });
  step("the template is synced", async () => {
    await listening;
    ran.contents = await TestCli.runs([
      "--registry",
      `http://127.0.0.1:` + port.contents.toString(),
      "--template",
      template
    ], scratch, Nodepath.join(TestCli.$$package, "bin/sync.mjs"));
  });
  step("the template names {string} at {string}", (name, spec) => Vitest.expect(named(template, name)).toBe(spec));
  step("the template names each dependency at a published version", table => {
    Vitest$1.toRecords(table).forEach(row => {
      let spec = named(template, row.dependency);
      let tags = published[row.dependency];
      let tagged = tags !== undefined ? Stdlib_Option.isSome(tags[spec]) : false;
      Vitest.expect([
        row.dependency,
        tagged || Semver.satisfies(served(row.dependency), spec)
      ]).toEqual([
        row.dependency,
        true
      ]);
    });
  });
  step("the template still names the project {string}", name => {
    let fields = JSON.parse(Nodefs.readFileSync(template, "utf8"));
    if (typeof fields === "object" && fields !== null && !Array.isArray(fields)) {
      return Vitest.expect(fields["name"]).toEqual(name);
    } else {
      return Stdlib_JsError.throwWithMessage("the template is not an object");
    }
  });
  step("the template still holds its scripts", () => {
    let fields = JSON.parse(Nodefs.readFileSync(template, "utf8"));
    if (typeof fields !== "object" || fields === null || Array.isArray(fields)) {
      return Stdlib_JsError.throwWithMessage("the template is not an object");
    }
    let match = fields["scripts"];
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      return Vitest.expect(Stdlib_Option.isSome(match["dev"])).toBe(true);
    } else {
      return Stdlib_JsError.throwWithMessage("the template holds no scripts");
    }
  });
  step("sync fails and reports {string}", text => {
    Vitest.expect(ran.contents.code === 0).toBe(false);
    Vitest.expect(ran.contents.complained).toContain(text);
  });
  step("sync fails and reports the registry", () => {
    Vitest.expect(ran.contents.code === 0).toBe(false);
    Vitest.expect(ran.contents.complained).toContain("127.0.0.1");
  });
  step("the template is unchanged", () => Vitest.expect(Nodefs.readFileSync(template, "utf8")).toBe(before));
});

export {
  raise,
  sections,
  specs,
  named,
}
/*  Not a pure module */
