// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodeos from "node:os";
import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Nodechild_process from "node:child_process";

function scratch() {
  return Nodefs.mkdtempSync(Nodepath.join(Nodeos.tmpdir(), "epure-test-"));
}

function forget(path) {
  Nodefs.rmSync(path, {
    recursive: true,
    force: true
  });
}

let System = {
  scratch: scratch,
  forget: forget
};

let $$package = Nodepath.resolve(Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url)), "../..");

let entry = Nodepath.join($$package, "bin/epure.mjs");

let links = [
  "--with",
  `@epure/dev=link:` + Nodepath.resolve($$package, "../dev")
];

function golden() {
  let fields = JSON.parse(Nodefs.readFileSync(Nodepath.join(Nodeos.tmpdir(), "epure-golden.json"), "utf8"));
  if (typeof fields !== "object" || fields === null || Array.isArray(fields)) {
    return Stdlib_JsError.throwWithMessage("no shared init was built");
  }
  let match = fields["project"];
  let match$1 = fields["radif"];
  if (typeof match === "string" && typeof match$1 === "string") {
    return {
      project: match,
      radif: match$1
    };
  } else {
    return Stdlib_JsError.throwWithMessage("the shared init names no project");
  }
}

async function runs(args, at, fromOpt) {
  let from = fromOpt !== undefined ? fromOpt : entry;
  let child = Nodechild_process.spawn("node", [from].concat(args), {
    cwd: at
  });
  let said = {
    contents: ""
  };
  let complained = {
    contents: ""
  };
  child.stdout.setEncoding("utf8");
  child.stdout.on("data", text => {
    said.contents = said.contents + text;
  });
  child.stderr.setEncoding("utf8");
  child.stderr.on("data", text => {
    complained.contents = complained.contents + text;
  });
  return await new Promise((resolve, _reject) => {
    child.on("close", code => resolve({
      said: said.contents,
      complained: complained.contents,
      code: Stdlib_Nullable.getOr(code, -1)
    }));
  });
}

export {
  System,
  $$package,
  entry,
  links,
  golden,
  runs,
}
/* package Not a pure module */
