// Generated by ReScript, PLEASE EDIT WITH CARE

import * as System from "./System.mjs";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Nodechild_process from "node:child_process";

let lapaPort = "8081";

let appPort = "8080";

let stopping = {
  contents: false
};

let children = [];

function stopAll() {
  stopping.contents = true;
  children.forEach(one => {
    one.kill("SIGTERM");
  });
}

function watch(name, one) {
  children.push(one);
  one.on("error", error => {
    if (!stopping.contents) {
      process.stderr.write(name + ` could not start: ` + error.message + `\n`);
      if (name === "lapa") {
        process.stderr.write("install @lapa/server, or set EPURE_LAPA_BIN to a checkout's server/bin/lapa.mjs\n");
      }
      stopAll();
      return System.failsWhenDone(1);
    }
  });
  one.on("close", code => {
    if (stopping.contents) {
      return;
    }
    process.stderr.write(name + ` stopped\n`);
    stopAll();
    let code$1 = Stdlib_Nullable.getOr(code, 1);
    process.exit(code$1 === 0 ? 1 : code$1);
  });
}

function sessionOf(line) {
  return Stdlib_Array.findMap(line.split(" "), word => {
    if (word.startsWith("session=")) {
      return word.slice("session=".length);
    }
  });
}

function settle(ms) {
  return new Promise((resolve, param) => {
    setTimeout(() => resolve(), ms);
  });
}

async function announce(token) {
  let address = `http://localhost:` + appPort + `/`;
  let probes = [
    `http://127.0.0.1:` + appPort + `/`,
    `http://[::1]:` + appPort + `/`
  ];
  let reached = async probe => {
    try {
      await fetch(probe);
      return true;
    } catch (exn) {
      return false;
    }
  };
  let waits = async left => {
    if (left <= 0) {
      return;
    }
    let answered = await Stdlib_Array.reduce(probes, Promise.resolve(false), async (found, probe) => {
      if (await found) {
        return true;
      } else {
        return await reached(probe);
      }
    });
    if (answered) {
      process.stdout.write(`\n` + Nodepath.basename(process.cwd()) + `  ` + address + `?lapa-session=` + token + `\n\n`);
      return;
    } else {
      await settle(100);
      return await waits(left - 1 | 0);
    }
  };
  return await waits(300);
}

function main() {
  if (!Nodefs.existsSync(Nodepath.join(process.cwd(), "package.json"))) {
    process.stderr.write("dev runs in a project; no package.json here\n");
    process.exit(1);
  }
  let vite = Nodepath.join(process.cwd(), "node_modules/.bin/vite");
  let rescript = Nodepath.join(process.cwd(), "node_modules/.bin/rescript");
  if (!Nodefs.existsSync(vite) || !Nodefs.existsSync(rescript)) {
    process.stderr.write("dev needs the project installed; run pnpm install\n");
    process.exit(1);
  }
  let lapa = Stdlib_Option.getOr(process.env["EPURE_LAPA_BIN"], "lapa");
  process.on("SIGTERM", () => stopAll());
  process.on("SIGINT", () => stopAll());
  watch("rescript", Nodechild_process.spawn(rescript, ["watch"], {
    cwd: process.cwd(),
    stdio: [
      "ignore",
      "inherit",
      "inherit"
    ]
  }));
  let served = Nodechild_process.spawn(lapa, [
    "dev",
    ".data",
    "--port",
    lapaPort
  ], {
    cwd: process.cwd(),
    stdio: [
      "ignore",
      "pipe",
      "pipe"
    ]
  });
  let seen = {
    contents: false
  };
  let hear = text => {
    process.stdout.write(text);
    if (seen.contents) {
      return;
    }
    let line = text.split("\n").find(line => line.startsWith("dev "));
    if (line !== undefined) {
      seen.contents = true;
      watch("vite", Nodechild_process.spawn(vite, [], {
        cwd: process.cwd(),
        stdio: [
          "ignore",
          "inherit",
          "inherit"
        ]
      }));
      return Stdlib_Option.forEach(sessionOf(line), token => {
        announce(token);
      });
    }
  };
  served.stdout.setEncoding("utf8");
  served.stdout.on("data", hear);
  served.stderr.setEncoding("utf8");
  served.stderr.on("data", prim => {
    process.stderr.write(prim);
  });
  watch("lapa", served);
}

export {
  lapaPort,
  appPort,
  stopping,
  children,
  stopAll,
  watch,
  sessionOf,
  settle,
  announce,
  main,
}
/* node:fs Not a pure module */
