// Generated by ReScript, PLEASE EDIT WITH CARE

import * as System from "./System.mjs";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Nodechild_process from "node:child_process";

let radifPort = "8081";

let appPort = "8080";

let modelDir = "src/domain/api/entity";

let stopping = {
  contents: false
};

let children = [];

function stopAll() {
  stopping.contents = true;
  children.forEach(one => {
    one.kill("SIGTERM");
  });
}

function watch(name, one) {
  children.push(one);
  one.on("error", error => {
    if (!stopping.contents) {
      process.stderr.write(name + ` could not start: ` + error.message + `\n`);
      if (name === "radif") {
        process.stderr.write("install @radif/server, or set EPURE_RADIF_BIN to a checkout's server/bin/radif.mjs\n");
      }
      stopAll();
      return System.failsWhenDone(1);
    }
  });
  one.on("close", code => {
    if (stopping.contents) {
      return;
    }
    process.stderr.write(name + ` stopped\n`);
    stopAll();
    let code$1 = Stdlib_Nullable.getOr(code, 1);
    process.exit(code$1 === 0 ? 1 : code$1);
  });
}

function sessionOf(line) {
  return Stdlib_Array.findMap(line.split(" "), word => {
    if (word.startsWith("session=")) {
      return word.slice("session=".length);
    }
  });
}

function settle(ms) {
  return new Promise((resolve, param) => {
    setTimeout(() => resolve(), ms);
  });
}

function connect(token) {
  let path = Nodepath.join(process.cwd(), ".mcp.json");
  let held;
  if (Nodefs.existsSync(path)) {
    let exit = 0;
    let fields;
    try {
      fields = JSON.parse(Nodefs.readFileSync(path, "utf8"));
      exit = 1;
    } catch (exn) {
      held = undefined;
    }
    if (exit === 1) {
      held = typeof fields === "object" && fields !== null && !Array.isArray(fields) ? fields : undefined;
    }
  } else {
    held = {};
  }
  if (held !== undefined) {
    let match = held["mcpServers"];
    let servers;
    let exit$1 = 0;
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      servers = match;
    } else {
      exit$1 = 1;
    }
    if (exit$1 === 1) {
      let servers$1 = {};
      held["mcpServers"] = servers$1;
      servers = servers$1;
    }
    servers["desk"] = Object.fromEntries([
      [
        "type",
        "http"
      ],
      [
        "url",
        `http://localhost:` + appPort + `/_radif/mcp`
      ],
      [
        "headers",
        Object.fromEntries([[
            "Authorization",
            token
          ]])
      ]
    ]);
    Nodefs.writeFileSync(path, JSON.stringify(held, undefined, 2) + "\n", {
      mode: 384
    });
    return;
  }
  process.stderr.write(".mcp.json is not JSON; dev leaves it and writes no desk entry\n");
}

async function announce(token) {
  let address = `http://localhost:` + appPort + `/`;
  let probes = [
    `http://127.0.0.1:` + appPort + `/`,
    `http://[::1]:` + appPort + `/`
  ];
  let reached = async probe => {
    try {
      await fetch(probe);
      return true;
    } catch (exn) {
      return false;
    }
  };
  let waits = async left => {
    if (left <= 0) {
      return;
    }
    let answered = await Stdlib_Array.reduce(probes, Promise.resolve(false), async (found, probe) => {
      if (await found) {
        return true;
      } else {
        return await reached(probe);
      }
    });
    if (answered) {
      process.stdout.write(`\n` + Nodepath.basename(process.cwd()) + `  ` + address + `?radif-session=` + token + `\n\n`);
      return;
    } else {
      await settle(100);
      return await waits(left - 1 | 0);
    }
  };
  return await waits(300);
}

function prepare() {
  let radif = Stdlib_Option.getOr(process.env["EPURE_RADIF_BIN"], "radif");
  let served = Nodechild_process.spawn(radif, [
    "dev",
    ".data",
    "--port",
    "0"
  ], {
    cwd: process.cwd(),
    stdio: [
      "ignore",
      "pipe",
      "pipe"
    ]
  });
  let seen = {
    contents: false
  };
  let skip = message => {
    process.stderr.write(`prepare skipped: ` + message + `\n`);
    return process.exit(0);
  };
  served.on("error", param => skip("radif could not start"));
  served.on("close", param => {
    if (!seen.contents) {
      return skip("radif stopped before it spoke");
    }
  });
  served.stdout.setEncoding("utf8");
  served.stdout.on("data", text => {
    if (seen.contents) {
      return;
    }
    let line = text.split("\n").find(line => line.startsWith("dev "));
    if (line !== undefined) {
      seen.contents = true;
      Stdlib_Option.forEach(sessionOf(line), connect);
      process.stdout.write(".mcp.json holds the desk\n");
      served.kill("SIGTERM");
      return;
    }
  });
  served.stderr.setEncoding("utf8");
  served.stderr.on("data", param => {});
  setTimeout(() => {
    if (!seen.contents) {
      served.kill("SIGTERM");
      return skip("radif said nothing");
    }
  }, 30000).unref();
}

function serve() {
  let vite = Nodepath.join(process.cwd(), "node_modules/.bin/vite");
  let rescript = Nodepath.join(process.cwd(), "node_modules/.bin/rescript");
  if (!Nodefs.existsSync(vite) || !Nodefs.existsSync(rescript)) {
    process.stderr.write("dev needs the project installed; run pnpm install\n");
    process.exit(1);
  }
  let radif = Stdlib_Option.getOr(process.env["EPURE_RADIF_BIN"], "radif");
  process.on("SIGTERM", () => stopAll());
  process.on("SIGINT", () => stopAll());
  watch("rescript", Nodechild_process.spawn(rescript, ["watch"], {
    cwd: process.cwd(),
    stdio: [
      "ignore",
      "inherit",
      "inherit"
    ]
  }));
  let served = Nodechild_process.spawn(radif, [
    "dev",
    ".data",
    "--port",
    radifPort,
    "--types",
    modelDir
  ], {
    cwd: process.cwd(),
    stdio: [
      "ignore",
      "pipe",
      "pipe"
    ]
  });
  let seen = {
    contents: false
  };
  let hear = text => {
    process.stdout.write(text);
    if (seen.contents) {
      return;
    }
    let line = text.split("\n").find(line => line.startsWith("dev "));
    if (line !== undefined) {
      seen.contents = true;
      watch("vite", Nodechild_process.spawn(vite, [], {
        cwd: process.cwd(),
        stdio: [
          "ignore",
          "inherit",
          "inherit"
        ]
      }));
      return Stdlib_Option.forEach(sessionOf(line), token => {
        connect(token);
        announce(token);
      });
    }
  };
  served.stdout.setEncoding("utf8");
  served.stdout.on("data", hear);
  served.stderr.setEncoding("utf8");
  served.stderr.on("data", prim => {
    process.stderr.write(prim);
  });
  watch("radif", served);
}

function main() {
  if (!Nodefs.existsSync(Nodepath.join(process.cwd(), "package.json"))) {
    process.stderr.write("dev runs in a project; no package.json here\n");
    process.exit(1);
  }
  let word = process.argv[2];
  if (word === undefined) {
    return serve();
  }
  if (word === "prepare") {
    return prepare();
  }
  process.stderr.write(`epure-dev knows no ` + word + `\n`);
  process.exit(1);
}

export {
  radifPort,
  appPort,
  modelDir,
  stopping,
  children,
  stopAll,
  watch,
  sessionOf,
  settle,
  connect,
  announce,
  prepare,
  serve,
  main,
}
/* node:fs Not a pure module */
