// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodechild_process from "node:child_process";

function templates() {
  return Nodepath.join(Nodepath.dirname(Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url))), "templates");
}

function files(dir) {
  return Nodefs.readdirSync(dir).flatMap(name => {
    let path = Nodepath.join(dir, name);
    if (Nodefs.statSync(path).isDirectory()) {
      return files(path).map(rest => Nodepath.join(name, rest));
    } else {
      return [name];
    }
  });
}

function landed(name) {
  if (name === "gitignore") {
    return ".gitignore";
  } else if (name.endsWith("gitkeep")) {
    return name.replace("gitkeep", ".gitkeep");
  } else {
    return name;
  }
}

function overrides(raw, withs) {
  let json = JSON.parse(raw);
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return raw;
  }
  let set = (section, $$package, spec) => {
    let match = json[section];
    if (match !== undefined && typeof match === "object" && match !== null && !Array.isArray(match) && Stdlib_Option.isSome(match[$$package])) {
      match[$$package] = spec;
      return true;
    } else {
      return false;
    }
  };
  withs.forEach(param => {
    let spec = param[1];
    let $$package = param[0];
    if (set("dependencies", $$package, spec) || set("devDependencies", $$package, spec)) {
      return;
    }
    let match = json["dependencies"];
    if (match === undefined) {
      return;
    }
    if (typeof match !== "object" || match === null || Array.isArray(match)) {
      return;
    }
    match[$$package] = spec;
  });
  return JSON.stringify(json, undefined, 2) + "\n";
}

function run(name, withs, registry) {
  let dir = Nodepath.resolve(process.cwd(), name);
  if (Nodefs.existsSync(dir) && Nodefs.readdirSync(dir).length !== 0) {
    process.stderr.write(`init refuses: ` + name + ` already holds files\n`);
    process.exit(1);
  }
  let from = templates();
  files(from).forEach(file => {
    let text = Nodefs.readFileSync(Nodepath.join(from, file), "utf8").replaceAll("{{name}}", name);
    let text$1 = file === "package.json" ? overrides(text, withs) : text;
    let target = Nodepath.join(dir, landed(file));
    Nodefs.mkdirSync(Nodepath.dirname(target), {
      recursive: true
    });
    Nodefs.writeFileSync(target, text$1);
  });
  Stdlib_Option.forEach(registry, url => {
    Nodefs.writeFileSync(Nodepath.join(dir, ".npmrc"), `registry=` + url + `\n`);
  });
  let installed = Nodechild_process.spawnSync("pnpm", ["install"], {
    cwd: dir,
    stdio: "inherit"
  });
  if (Primitive_object.notequal(Primitive_option.fromNullable(installed.status), 0)) {
    process.stderr.write(`init could not install in ` + name + `\n`);
    process.exit(1);
  }
  process.stdout.write(name + ` is ready\n`);
}

export {
  templates,
  files,
  landed,
  overrides,
  run,
}
/* node:fs Not a pure module */
