// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dev from "./Dev.mjs";
import * as Init from "./Init.mjs";
import * as Stdlib_String from "@rescript/runtime/lib/es6/Stdlib_String.js";

let usage = "epure <init|dev>\n  init <name> [--with package=spec]\n  dev\n";

function withsOf(args) {
  let withs = [];
  let walk = _index => {
    while (true) {
      let index = _index;
      let match = args[index];
      let match$1 = args[index + 1 | 0];
      if (match === undefined) {
        return;
      }
      if (match === "--with") {
        if (match$1 !== undefined) {
          let at = Stdlib_String.indexOfOpt(match$1, "=");
          if (at !== undefined) {
            withs.push([
              match$1.slice(0, at),
              match$1.slice(at + 1 | 0)
            ]);
          }
          _index = index + 2 | 0;
          continue;
        }
        _index = index + 1 | 0;
        continue;
      }
      _index = index + 1 | 0;
      continue;
    };
  };
  walk(0);
  return withs;
}

function main() {
  let args = process.argv.slice(2);
  let match = args[0];
  let match$1 = args[1];
  if (match !== undefined) {
    switch (match) {
      case "dev" :
        return Dev.main();
      case "init" :
        if (match$1 !== undefined && !match$1.startsWith("-")) {
          return Init.run(match$1, withsOf(args));
        }
        break;
    }
  }
  process.stderr.write(usage);
  process.exit(1);
}

export {
  usage,
  withsOf,
  main,
}
/* Dev Not a pure module */
