// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Init from "./Init.mjs";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_String from "@rescript/runtime/lib/es6/Stdlib_String.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function flagged(args, name) {
  let _index = 0;
  while (true) {
    let index = _index;
    let match = args[index];
    let match$1 = args[index + 1 | 0];
    if (match === undefined) {
      return;
    }
    if (match$1 !== undefined) {
      if (match === name) {
        return match$1;
      }
      _index = index + 1 | 0;
      continue;
    }
    _index = index + 1 | 0;
    continue;
  };
}

function registry(args) {
  let url = flagged(args, "--registry");
  let url$1;
  if (url !== undefined) {
    url$1 = url;
  } else {
    let url$2 = process.env["npm_config_registry"];
    url$1 = url$2 !== undefined && url$2 !== "" ? url$2 : "https://registry.npmjs.org";
  }
  if (url$1.endsWith("/")) {
    return url$1.slice(0, url$1.length - 1 | 0);
  } else {
    return url$1;
  }
}

function split(version) {
  let at = Stdlib_String.indexOfOpt(version, "-");
  if (at !== undefined) {
    return [
      version.slice(0, at),
      version.slice(at + 1 | 0)
    ];
  } else {
    return [
      version,
      undefined
    ];
  }
}

function named(version) {
  let match = split(version);
  let pre = match[1];
  if (pre !== undefined) {
    return Stdlib_Option.getOr(pre.split(".")[0], "beta");
  } else {
    return `^` + version;
  }
}

function wanted(spec) {
  let bare = spec.replace("^", "");
  let match = Stdlib_Int.fromString(bare.slice(0, 1), undefined);
  if (match === undefined) {
    return bare;
  }
  let match$1 = split(bare);
  let pre = match$1[1];
  if (pre !== undefined) {
    return Stdlib_Option.getOr(pre.split(".")[0], "latest");
  } else {
    return "latest";
  }
}

async function asked(registry, $$package) {
  let url = registry + `/` + $$package.replaceAll("/", "%2f");
  let answer;
  try {
    answer = await fetch(url, {
      headers: {
        accept: "application/json"
      }
    });
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === "JsExn") {
      answer = Stdlib_JsError.throwWithMessage(`sync cannot reach ` + registry + `: ` + Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "no answer"));
    } else {
      throw error;
    }
  }
  if (!answer.ok) {
    Stdlib_JsError.throwWithMessage(`sync found no ` + $$package + ` on ` + registry);
  }
  return await answer.json();
}

function taken(packument, $$package, tag) {
  let tags;
  if (typeof packument === "object" && packument !== null && !Array.isArray(packument)) {
    let match = packument["dist-tags"];
    tags = match !== undefined ? (
        typeof match === "object" && match !== null && !Array.isArray(match) ? match : ({})
      ) : ({});
  } else {
    tags = {};
  }
  let at = name => {
    let match = tags[name];
    if (typeof match === "string") {
      return match;
    }
  };
  let version = at(tag);
  if (version !== undefined) {
    return version;
  }
  let version$1 = at(tag === "latest" ? "beta" : "latest");
  if (version$1 !== undefined) {
    return version$1;
  } else {
    return Stdlib_JsError.throwWithMessage(`sync found no ` + $$package + ` on any line`);
  }
}

let sections = [
  "dependencies",
  "devDependencies"
];

async function main() {
  let args = process.argv.slice(2);
  let registry$1 = registry(args);
  let path = flagged(args, "--template");
  let file = path !== undefined ? path : Nodepath.join(Init.templates(), "package.json");
  let raw = Nodefs.readFileSync(file, "utf8");
  let json = JSON.parse(raw);
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let specs = [];
    sections.forEach(section => {
      let match = json[section];
      if (match === undefined) {
        return;
      }
      if (typeof match !== "object" || match === null || Array.isArray(match)) {
        return;
      }
      Object.entries(match).forEach(param => {
        let spec = param[1];
        if (typeof spec !== "string") {
          return;
        }
        specs.push([
          match,
          param[0],
          spec
        ]);
      });
    });
    let found;
    try {
      found = await Promise.all(specs.map(async param => {
        let spec = param[2];
        let $$package = param[1];
        let tag = wanted(spec);
        let packument = await asked(registry$1, $$package);
        return [
          param[0],
          $$package,
          spec,
          named(taken(packument, $$package, tag))
        ];
      }));
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === "JsExn") {
        process.stderr.write(Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "sync failed") + `\n`);
        found = process.exit(1);
      } else {
        throw error;
      }
    }
    found.forEach(param => {
      let range = param[3];
      let spec = param[2];
      let $$package = param[1];
      if (spec !== range) {
        process.stdout.write($$package + ` ` + spec + ` -> ` + range + `\n`);
      }
      param[0][$$package] = range;
    });
    Nodefs.writeFileSync(file, JSON.stringify(json, undefined, 2) + "\n");
    process.stdout.write(`the template is synced with ` + registry$1 + `\n`);
    return;
  }
  process.stderr.write("sync found no template package.json\n");
  return process.exit(1);
}

export {
  flagged,
  registry,
  split,
  named,
  wanted,
  asked,
  taken,
  sections,
  main,
}
/* Init Not a pure module */
