// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodeos from "node:os";
import * as Nodepath from "node:path";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_String from "@rescript/runtime/lib/es6/Stdlib_String.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodechild_process from "node:child_process";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let raise = Stdlib_JsError.throwWithMessage;

function settle(ms) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve(), ms);
  });
}

function binary() {
  let path = process.env["CHROME"];
  let named = path !== undefined ? (
      path !== "" ? [path] : []
    ) : [];
  let known = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
  ];
  let path$1 = named.concat(known).find(prim => Nodefs.existsSync(prim));
  if (path$1 !== undefined) {
    return path$1;
  } else {
    return Stdlib_JsError.throwWithMessage("these scenarios need a browser, and none was found. Install Chrome, or name one in CHROME.");
  }
}

function field(json, name) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    return json[name];
  }
}

function text(json) {
  if (typeof json === "string") {
    return json;
  } else {
    return "";
  }
}

function listening(said) {
  return Stdlib_Array.findMap(said.split("\n"), line => {
    let at = Stdlib_String.indexOfOpt(line, "ws://");
    if (at !== undefined) {
      return line.slice(at).trim();
    }
  });
}

async function waitsFor(check, everyOpt, leftOpt) {
  let every = everyOpt !== undefined ? everyOpt : 100;
  let left = leftOpt !== undefined ? leftOpt : 100;
  let found = await check();
  if (found !== undefined) {
    return Primitive_option.valFromOption(found);
  } else {
    if (left === 0) {
      Stdlib_JsError.throwWithMessage("the browser did not answer in time");
    }
    await settle(every);
    return await waitsFor(check, every, left - 1 | 0);
  }
}

async function opens() {
  let profile = Nodefs.mkdtempSync(Nodepath.join(Nodeos.tmpdir(), "epure-browser-"));
  let child = Nodechild_process.spawn(binary(), [
    "--headless=new",
    "--disable-gpu",
    "--no-sandbox",
    "--no-first-run",
    "--disable-extensions",
    "--remote-debugging-port=0",
    `--user-data-dir=` + profile,
    "about:blank"
  ], {
    cwd: Nodeos.tmpdir()
  });
  let said = {
    contents: ""
  };
  child.stderr.setEncoding("utf8");
  child.stderr.on("data", line => {
    said.contents = said.contents + line;
  });
  let endpoint = await waitsFor(async () => listening(said.contents), undefined, undefined);
  let port = Stdlib_Option.getOr(Stdlib_Option.getOr(endpoint.split("/")[2], "").split(":")[1], "");
  let target = await waitsFor(async () => {
    let answer;
    try {
      answer = await fetch(`http://127.0.0.1:` + port + `/json/list`);
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      if (exn.RE_EXN_ID === "JsExn") {
        return;
      }
      throw exn;
    }
    let list = await answer.json();
    if (Array.isArray(list)) {
      return list.find(one => text(field(one, "type")) === "page");
    }
  }, undefined, undefined);
  let socket = new WebSocket(text(field(target, "webSocketDebuggerUrl")));
  let complaints = [];
  let sockets = [];
  let waiting = {};
  let counter = {
    contents: 0
  };
  socket.onmessage = message => {
    let json = JSON.parse(message.data);
    let match = field(json, "id");
    if (typeof match === "number") {
      let answer = waiting[match.toString()];
      if (answer !== undefined) {
        Stdlib_Dict.$$delete(waiting, match.toString());
        return answer(Stdlib_Option.getOr(field(json, "result"), null));
      } else {
        return;
      }
    }
    let params = Stdlib_Option.getOr(field(json, "params"), null);
    let match$1 = text(field(json, "method"));
    switch (match$1) {
      case "Log.entryAdded" :
        let entry = Stdlib_Option.getOr(field(params, "entry"), null);
        if (text(field(entry, "level")) === "error") {
          complaints.push("log: " + text(field(entry, "text")));
          return;
        } else {
          return;
        }
      case "Network.webSocketCreated" :
        sockets.push([
          text(field(params, "requestId")),
          text(field(params, "url")),
          {
            contents: false
          }
        ]);
        return;
      case "Network.webSocketHandshakeResponseReceived" :
        sockets.forEach(param => {
          if (param[0] === text(field(params, "requestId"))) {
            param[2].contents = true;
            return;
          }
        });
        return;
      case "Runtime.consoleAPICalled" :
        if (text(field(params, "type")) === "error") {
          complaints.push("console: " + JSON.stringify(params));
          return;
        } else {
          return;
        }
      case "Runtime.exceptionThrown" :
        complaints.push("thrown: " + text(Stdlib_Option.flatMap(field(params, "exceptionDetails"), one => field(one, "text"))));
        return;
      default:
        return;
    }
  };
  await new Promise((resolve, _reject) => {
    socket.onopen = () => resolve();
  });
  let ask = (method_, params) => {
    counter.contents = counter.contents + 1 | 0;
    let id = counter.contents;
    let answer = new Promise((resolve, _reject) => {
      waiting[id.toString()] = resolve;
    });
    socket.send(JSON.stringify(Object.fromEntries([
      [
        "id",
        id
      ],
      [
        "method",
        method_
      ],
      [
        "params",
        params
      ]
    ])));
    return answer;
  };
  let page = {
    child: child,
    socket: socket,
    complaints: complaints,
    sockets: sockets,
    ask: ask
  };
  let none = {};
  await ask("Runtime.enable", none);
  await ask("Log.enable", none);
  await ask("Network.enable", none);
  await ask("Page.enable", none);
  return page;
}

async function goes(page, address) {
  await page.ask("Page.navigate", Object.fromEntries([[
      "url",
      address
    ]]));
}

async function reads(page, expression) {
  let answer = await page.ask("Runtime.evaluate", Object.fromEntries([
    [
      "expression",
      expression
    ],
    [
      "returnByValue",
      true
    ],
    [
      "awaitPromise",
      true
    ]
  ]));
  return text(Stdlib_Option.flatMap(field(answer, "result"), one => field(one, "value")));
}

async function drew(page, withinOpt) {
  let within = withinOpt !== undefined ? withinOpt : 15000;
  let tries = within / 250 | 0;
  let look = async left => {
    let drawn = await reads(page, "document.getElementById('root').innerHTML");
    if (drawn === "") {
      if (left === 0) {
        return "";
      } else {
        await settle(250);
        return await look(left - 1 | 0);
      }
    } else {
      return drawn;
    }
  };
  return await look(tries);
}

function shuts(page) {
  page.socket.close();
  page.child.kill("SIGKILL");
}

export {
  raise,
  settle,
  binary,
  field,
  text,
  listening,
  waitsFor,
  opens,
  goes,
  reads,
  drew,
  shuts,
}
/* node:fs Not a pure module */
