// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Browser from "./Browser.mjs";
import * as TestCli from "./TestCli.mjs";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Vitest$1 from "@epure/vitest";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodechild_process from "node:child_process";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let raise = Stdlib_JsError.throwWithMessage;

function settle(ms) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve(), ms);
  });
}

async function until(check, leftOpt) {
  let left = leftOpt !== undefined ? leftOpt : 150;
  if (!await check()) {
    if (left === 0) {
      Stdlib_JsError.throwWithMessage("nothing answered in time");
    }
    await settle(100);
    return await until(check, left - 1 | 0);
  }
}

let app = "http://127.0.0.1:8080";

async function answers(route) {
  let response;
  try {
    response = await fetch(app + route);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return;
    }
    throw exn;
  }
  return response;
}

function wordAfter(words, name) {
  return Stdlib_Array.findMap(words, word => {
    if (word.startsWith(name + "=")) {
      return word.slice(name.length + 1 | 0);
    }
  });
}

Vitest$1.Given("a project created by init that nothing serves", (param, context) => {
  let step = param.step;
  let where = TestCli.golden();
  let project = where.project;
  let data = Nodepath.join(project, ".data");
  let mcp = Nodepath.join(project, ".mcp.json");
  TestCli.System.forget(data);
  TestCli.System.forget(mcp);
  let current = {
    contents: undefined
  };
  let listening = {
    contents: undefined
  };
  let browsing = {
    contents: undefined
  };
  let lastStatus = {
    contents: 0
  };
  let lastBody = {
    contents: ""
  };
  let running = () => {
    let server = current.contents;
    if (server !== undefined) {
      return server;
    } else {
      return Stdlib_JsError.throwWithMessage("no dev was started");
    }
  };
  context.onTestFinished(async param => {
    Stdlib_Option.forEach(browsing.contents, Browser.shuts);
    Stdlib_Option.forEach(listening.contents, param => {
      param[0].close();
    });
    let server = current.contents;
    if (server !== undefined && !server.gone.contents) {
      let quiet = new Promise((resolve, _reject) => {
        server.child.on("close", param => resolve());
      });
      server.child.kill("SIGTERM");
      await quiet;
    }
    TestCli.System.forget(data);
    return TestCli.System.forget(mcp);
  });
  let starts = async () => {
    let env = Object.assign({}, process.env);
    env["EPURE_LAPA_BIN"] = where.lapa;
    let server_child = Nodechild_process.spawn("node", [TestCli.entry], {
      cwd: project,
      env: env
    });
    let server_said = {
      contents: ""
    };
    let server_complained = {
      contents: ""
    };
    let server_session = {
      contents: ""
    };
    let server_code = {
      contents: ""
    };
    let server_gone = {
      contents: false
    };
    let server_exit = {
      contents: -1
    };
    let server = {
      child: server_child,
      said: server_said,
      complained: server_complained,
      session: server_session,
      code: server_code,
      gone: server_gone,
      exit: server_exit
    };
    let hear = text => {
      server_said.contents = server_said.contents + text;
      Stdlib_Option.forEach(server_said.contents.split("\n").find(line => line.startsWith("dev ")), line => {
        let words = line.trim().split(" ");
        Stdlib_Option.forEach(wordAfter(words, "session"), token => {
          server_session.contents = token;
        });
        Stdlib_Option.forEach(wordAfter(words, "code"), code => {
          server_code.contents = code;
        });
      });
    };
    server_child.stdout.setEncoding("utf8");
    server_child.stdout.on("data", hear);
    server_child.stderr.setEncoding("utf8");
    server_child.stderr.on("data", text => {
      server_complained.contents = server_complained.contents + text;
    });
    server_child.on("close", code => {
      server_gone.contents = true;
      server_exit.contents = Stdlib_Nullable.getOr(code, -1);
    });
    current.contents = server;
    await until(async () => {
      if (server_session.contents !== "") {
        return true;
      } else {
        return server_gone.contents;
      }
    }, undefined);
    await until(async () => {
      if (Stdlib_Option.isSome(await answers("/"))) {
        return true;
      } else {
        return server_gone.contents;
      }
    }, undefined);
    if (server_gone.contents) {
      Stdlib_JsError.throwWithMessage("dev stopped early: " + server_complained.contents + server_said.contents);
    }
    return server;
  };
  let meta = name => {
    let fields = JSON.parse(Nodefs.readFileSync(Nodepath.join(data, "dev.json"), "utf8"));
    if (typeof fields !== "object" || fields === null || Array.isArray(fields)) {
      return Stdlib_JsError.throwWithMessage("dev.json is not an object");
    }
    let match = fields[name];
    if (typeof match === "string") {
      return match;
    }
    return Stdlib_JsError.throwWithMessage(`dev.json names no ` + name);
  };
  let asks = async (route, method, token, sent) => {
    let headers = {};
    Stdlib_Option.forEach(token, token => {
      headers["Authorization"] = token;
    });
    let response;
    try {
      response = await fetch(app + route, {
        method: method,
        headers: headers,
        body: sent
      });
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      if (exn.RE_EXN_ID === "JsExn") {
        lastStatus.contents = 0;
        lastBody.contents = "";
        return;
      }
      throw exn;
    }
    lastStatus.contents = response.status;
    lastBody.contents = await response.text();
  };
  let posts = async (route, token, message) => await asks(route, "POST", token, JSON.stringify(message));
  let calls = async (route, name, $$arguments) => await posts(route, running().session.contents, Object.fromEntries([
    [
      "jsonrpc",
      "2.0"
    ],
    [
      "id",
      1.0
    ],
    [
      "method",
      "tools/call"
    ],
    [
      "params",
      Object.fromEntries([
        [
          "name",
          name
        ],
        [
          "arguments",
          $$arguments
        ]
      ])
    ]
  ]));
  step("Theo runs dev", async () => {
    await starts();
  });
  step("a running dev", async () => {
    await starts();
  });
  step("the app page answers on the app port", async () => {
    await asks("/", undefined, undefined, undefined);
    Vitest.expect(lastStatus.contents).toBe(200);
    return Vitest.expect(lastBody.contents).toContain("adventure");
  });
  step("dev prints the code", () => Vitest.expect(running().code.contents.length > 0).toBe(true));
  let linesWithLink = () => running().said.contents.split("\n").filter(line => line.includes("?lapa-session="));
  let awaitsLink = async () => {
    await until(async () => linesWithLink().length !== 0, undefined);
    return linesWithLink()[0];
  };
  let link = async () => {
    let line = await awaitsLink();
    return Stdlib_Option.getOrThrow(line.trim().split(" ").find(word => word.startsWith("http://")), undefined);
  };
  step("dev prints one link", async () => {
    await awaitsLink();
    return Vitest.expect(linesWithLink().length).toBe(1);
  });
  step("the link is the app page on the app port", async () => {
    let address = await link();
    return Vitest.expect(address.startsWith("http://localhost:8080/")).toBe(true);
  });
  step("the link carries the session as {string}", async name => {
    let address = await link();
    return Vitest.expect(address.includes(`?` + name + `=`)).toBe(true);
  });
  step("the link begins with {string}", async scheme => Vitest.expect((await link()).startsWith(scheme)).toBe(true));
  step("the line holding the link names the project", async () => {
    let line = await awaitsLink();
    return Vitest.expect(line).toContain(Nodepath.basename(TestCli.golden().project));
  });
  step("fetching the link answers the app page", async () => {
    let address = await link();
    let answer = await fetch(address);
    Vitest.expect(answer.status).toBe(200);
    return Vitest.expect(await answer.text()).toContain("adventure");
  });
  step("the link carries the session dev printed", async () => {
    let address = await link();
    return Vitest.expect(address).toContain(running().session.contents);
  });
  let objectAt = (fields, name) => {
    let match = fields[name];
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      return match;
    }
    return Stdlib_JsError.throwWithMessage(`.mcp.json names no ` + name);
  };
  let stringAt = (fields, name) => {
    let match = fields[name];
    if (typeof match === "string") {
      return match;
    }
    return Stdlib_JsError.throwWithMessage(`the entry names no ` + name);
  };
  let servers = () => {
    let fields = JSON.parse(Nodefs.readFileSync(mcp, "utf8"));
    if (typeof fields === "object" && fields !== null && !Array.isArray(fields)) {
      return objectAt(fields, "mcpServers");
    } else {
      return Stdlib_JsError.throwWithMessage(".mcp.json is not an object");
    }
  };
  let planted = {
    contents: ""
  };
  step(".mcp.json names the desk at {string}", address => {
    let desk = objectAt(servers(), "desk");
    Vitest.expect(stringAt(desk, "type")).toBe("http");
    Vitest.expect(stringAt(desk, "url")).toBe(address);
  });
  step("the desk's authorization is the session dev printed", () => {
    let headers = objectAt(objectAt(servers(), "desk"), "headers");
    Vitest.expect(stringAt(headers, "Authorization")).toBe(running().session.contents);
  });
  step("a .mcp.json naming another server", () => {
    Nodefs.writeFileSync(mcp, `{"mcpServers":{"notes":{"type":"http","url":"http://localhost:9999/mcp"}}}\n`);
  });
  step(".mcp.json still names the other server", () => {
    let notes = objectAt(servers(), "notes");
    Vitest.expect(stringAt(notes, "url")).toBe("http://localhost:9999/mcp");
  });
  step("a .mcp.json that is not JSON", () => {
    planted.contents = "not json\n";
    Nodefs.writeFileSync(mcp, planted.contents);
  });
  step(".mcp.json is unchanged", () => Vitest.expect(Nodefs.readFileSync(mcp, "utf8")).toBe(planted.contents));
  step("dev warns that .mcp.json is not JSON", async () => await until(async () => running().complained.contents.includes(".mcp.json is not JSON"), undefined));
  let prepared = {
    contents: -1
  };
  let prepares = async () => {
    let env = Object.assign({}, process.env);
    env["EPURE_LAPA_BIN"] = where.lapa;
    let child = Nodechild_process.spawn("node", [
      TestCli.entry,
      "prepare"
    ], {
      cwd: project,
      env: env
    });
    prepared.contents = await new Promise((resolve, _reject) => {
      child.on("close", code => resolve(Stdlib_Nullable.getOr(code, -1)));
    });
  };
  step("Theo runs prepare", async () => await prepares());
  step("Theo ran prepare", async () => await prepares());
  step("prepare exits with {number}", expected => Vitest.expect(prepared.contents).toBe(expected | 0));
  let authorization = () => stringAt(objectAt(objectAt(servers(), "desk"), "headers"), "Authorization");
  step("the desk's authorization is the session the boot kept", () => Vitest.expect(authorization()).toBe(meta("session")));
  step("the link carries the session .mcp.json names", async () => {
    let named = authorization();
    return Vitest.expect((await link()).includes(named)).toBe(true);
  });
  step("a client pulling with that session answers the boot's rows", async () => {
    let address = await link();
    let token = address.split("lapa-session=")[1].split("&")[0];
    return await asks(`/_lapa/query?under=` + encodeURIComponent(meta("workspace")), undefined, token, undefined);
  });
  step("a client pulls through {string} with the founder's session", async prefix => await asks(prefix + `query?under=` + encodeURIComponent(meta("workspace")), undefined, running().session.contents, undefined));
  step("the pull answers the boot's rows", () => {
    Vitest.expect(lastStatus.contents).toBe(200);
    Vitest.expect(lastBody.contents).toContain("entities");
  });
  step("the agent lists the tools at {string} with the founder's session", async route => await posts(route, running().session.contents, Object.fromEntries([
    [
      "jsonrpc",
      "2.0"
    ],
    [
      "id",
      1.0
    ],
    [
      "method",
      "tools/list"
    ]
  ])));
  step("the desk's tools answer", () => {
    Vitest.expect(lastStatus.contents).toBe(200);
    Vitest.expect(lastBody.contents).toContain("define");
    Vitest.expect(lastBody.contents).toContain("export");
  });
  step("the agent lists the tools at {string} with no session", async route => await posts(route, undefined, Object.fromEntries([
    [
      "jsonrpc",
      "2.0"
    ],
    [
      "id",
      1.0
    ],
    [
      "method",
      "tools/list"
    ]
  ])));
  step("the answer is a refusal", () => Vitest.expect(lastStatus.contents).toBe(403));
  step("a client listening through {string}", async prefix => {
    let heard = [];
    let socket = new WebSocket(`ws://127.0.0.1:8080` + prefix + `listen?session=` + running().session.contents);
    let opened = {
      contents: false
    };
    socket.onopen = () => {
      opened.contents = true;
    };
    socket.onmessage = message => {
      heard.push(message.data);
    };
    listening.contents = [
      socket,
      heard
    ];
    return await until(async () => opened.contents, undefined);
  });
  step("the agent makes an entity at {string}", async route => {
    await calls(route, "define", Object.fromEntries([[
        "classes",
        [Object.fromEntries([
            [
              "title",
              "Adventure"
            ],
            [
              "fields",
              [Object.fromEntries([
                  [
                    "title",
                    "price"
                  ],
                  [
                    "kind",
                    "Number"
                  ]
                ])]
            ]
          ])]
      ]]));
    Vitest.expect(lastStatus.contents).toBe(200);
    await calls(route, "make", Object.fromEntries([
      [
        "class",
        "Adventure"
      ],
      [
        "title",
        "Raft Run"
      ],
      [
        "parts",
        Object.fromEntries([[
            "Adventure",
            Object.fromEntries([[
                "price",
                Object.fromEntries([[
                    "n",
                    12.0
                  ]])
              ]])
          ]])
      ]
    ]));
    return Vitest.expect(lastStatus.contents).toBe(200);
  });
  step("the client hears a stamp", async () => {
    let listener = listening.contents;
    let match = listener !== undefined ? listener : Stdlib_JsError.throwWithMessage("no client is listening");
    let heard = match[1];
    return await until(async () => heard.length !== 0, undefined);
  });
  step("the client's pull answers the entity", async () => {
    await asks(`/_lapa/query?under=` + encodeURIComponent(meta("workspace")), undefined, running().session.contents, undefined);
    Vitest.expect(lastStatus.contents).toBe(200);
    return Vitest.expect(lastBody.contents).toContain("Raft Run");
  });
  step("Theo changes the page's text to {string}", text => {
    let page = Nodepath.join(project, "src/view/Page.res");
    let original = Nodefs.readFileSync(page, "utf8");
    context.onTestFinished(async param => {
      Nodefs.writeFileSync(page, original);
    });
    let said = "this page opens on a session";
    if (!original.includes(said)) {
      Stdlib_JsError.throwWithMessage(`the page no longer says "` + said + `"`);
    }
    Nodefs.writeFileSync(page, original.replace(said, text));
  });
  step("the served page script says {string}", async wanted => await until(async () => {
    let response = await answers("/src/view/Page.res.mjs");
    if (response !== undefined && response.status === 200) {
      return (await response.text()).includes(wanted);
    } else {
      return false;
    }
  }, undefined));
  step("Theo runs dev without a lapa binary", async () => {
    let env = Object.assign({}, process.env);
    Stdlib_Dict.$$delete(env, "EPURE_LAPA_BIN");
    let child = Nodechild_process.spawn("node", [TestCli.entry], {
      cwd: project,
      env: env
    });
    let complained = {
      contents: ""
    };
    child.stderr.setEncoding("utf8");
    child.stderr.on("data", text => {
      complained.contents = complained.contents + text;
    });
    let exit = await new Promise((resolve, _reject) => {
      child.on("close", code => resolve(Stdlib_Nullable.getOr(code, -1)));
    });
    lastStatus.contents = exit;
    lastBody.contents = complained.contents;
  });
  step("dev exits and says lapa is missing", () => {
    Vitest.expect(lastStatus.contents === 0).toBe(false);
    Vitest.expect(lastBody.contents).toContain("lapa");
  });
  step("the compiler is not left running", () => {
    let built = Nodechild_process.spawnSync(Nodepath.join(project, "node_modules/.bin/rescript"), ["build"], {
      cwd: project,
      stdio: "pipe",
      encoding: "utf8"
    });
    let status = Stdlib_Option.getOr(Primitive_option.fromNullable(built.status), -1);
    if (status !== 0) {
      console.error(built.stdout);
      console.error(built.stderr);
    }
    Vitest.expect(status).toBe(0);
  });
  let browser = () => {
    let page = browsing.contents;
    if (page !== undefined) {
      return page;
    } else {
      return Stdlib_JsError.throwWithMessage("no browser was opened");
    }
  };
  let opensAt = async address => {
    let page = await Browser.opens();
    browsing.contents = page;
    await Browser.goes(page, address);
    return page;
  };
  step("Theo opens the link in a browser", async () => {
    await opensAt(await link());
  });
  step("Theo opens the app with no session in a browser", async () => {
    await opensAt(app + "/");
  });
  step("the page draws the app", async () => {
    let drawn = await Browser.drew(browser(), undefined);
    if (drawn === "") {
      console.error(browser().complaints.join("\n"));
      console.error(browser().sockets.map(param => param[1]).join("\n"));
    }
    Vitest.expect(drawn === "").toBe(false);
    return Vitest.expect(drawn).toContain("Hello");
  });
  step("the browser reports nothing wrong", () => Vitest.expect(browser().complaints.filter(one => !one.includes("favicon"))).toEqual([]));
  step("the app opens one socket under {string}", async prefix => {
    let page = browser();
    await until(async () => page.sockets.some(param => param[1].includes("session=")), undefined);
    let wire = page.sockets.filter(param => param[1].includes("session=")).map(param => param[1]);
    Vitest.expect(wire.length).toBe(1);
    return Vitest.expect(wire[0]).toContain(prefix);
  });
  step("the server answers that socket", async () => {
    let page = browser();
    let wire = () => page.sockets.filter(param => param[1].includes("session="));
    await until(async () => wire().every(param => param[2].contents), undefined);
    return Vitest.expect(wire().every(param => param[2].contents)).toBe(true);
  });
  step("the page says {string}", async wanted => {
    let drawn = await Browser.drew(browser(), undefined);
    return Vitest.expect(drawn).toContain(wanted);
  });
  step("Theo sends SIGTERM to dev", async () => {
    let server = running();
    let quiet = new Promise((resolve, _reject) => {
      server.child.on("close", param => resolve());
    });
    server.child.kill("SIGTERM");
    return await quiet;
  });
  step("dev exits with {number}", expected => {
    Vitest.expect(running().gone.contents).toBe(true);
    Vitest.expect(running().exit.contents).toBe(expected | 0);
  });
  step("the app port no longer answers", async () => await until(async () => Stdlib_Option.isNone(await answers("/")), undefined));
  step("the data directory is free to serve again", async () => {
    let probe = Nodechild_process.spawn(where.lapa, [
      "dev",
      ".data",
      "--port",
      "0"
    ], {
      cwd: project
    });
    let said = {
      contents: ""
    };
    probe.stdout.setEncoding("utf8");
    probe.stdout.on("data", text => {
      said.contents = said.contents + text;
    });
    await until(async () => said.contents.includes("dev "), undefined);
    let quiet = new Promise((resolve, _reject) => {
      probe.on("close", param => resolve());
    });
    probe.kill("SIGTERM");
    return await quiet;
  });
  step("lapa dev dies", async () => {
    Nodechild_process.spawnSync("pkill", [
      "-9",
      "-f",
      "lapa.mjs dev .data"
    ], {
      stdio: "ignore"
    });
    let server = running();
    return await until(async () => server.gone.contents, undefined);
  });
  step("dev exits and says lapa stopped", () => {
    Vitest.expect(running().gone.contents).toBe(true);
    Vitest.expect(running().exit.contents === 0).toBe(false);
    Vitest.expect(running().complained.contents).toContain("lapa stopped");
  });
});

export {
  raise,
  settle,
  until,
  app,
  answers,
  wordAfter,
}
/*  Not a pure module */
