// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodeos from "node:os";
import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function forget(path) {
  Nodefs.rmSync(path, {
    recursive: true,
    force: true
  });
}

let System = {
  forget: forget
};

let $$package = Nodepath.resolve(Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url)), "../..");

let entry = Nodepath.join($$package, "bin/epure-dev.mjs");

function golden() {
  let fields = JSON.parse(Nodefs.readFileSync(Nodepath.join(Nodeos.tmpdir(), "epure-dev-golden.json"), "utf8"));
  if (typeof fields !== "object" || fields === null || Array.isArray(fields)) {
    return Stdlib_JsError.throwWithMessage("no shared init was built");
  }
  let match = fields["project"];
  let match$1 = fields["lapa"];
  if (typeof match === "string" && typeof match$1 === "string") {
    return {
      project: match,
      lapa: match$1
    };
  } else {
    return Stdlib_JsError.throwWithMessage("the shared init names no project");
  }
}

export {
  System,
  $$package,
  entry,
  golden,
}
/* package Not a pure module */
